services:
  nginx:
    image: nginx:latest
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./web/src:/usr/share/nginx/html  # Mount the web/src directory to the NGINX document root
    depends_on:
      - socketio-x1
      - socketio-x2

  socketio-x1:
    platform: linux/amd64
    build:
      context: ./services/socketio
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - task-worker
      - redis
    environment:
      - REDIS_HOST=redis
      - PORT=3001
    command: ["npm", "start"]

  socketio-x2:
    platform: linux/amd64
    build:
      context: ./services/socketio
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    depends_on:
      - task-worker
      - redis
    environment:
      - REDIS_HOST=redis
      - PORT=3002
    command: ["npm", "start"]

  redis:
    image: redis:latest
    platform: linux/amd64
    ports:
      - "6379:6379"
    hostname: redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 5s
      retries: 2

  task-worker:
    platform: linux/amd64
    build:
      context: ./services/task-worker
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    volumes:
      - ./services/task-worker:/usr/src/app
