version: '3.8'

services:
  socketio:
    platform: linux/amd64
    build:
      context: ./services/socketio
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - task-worker
      - redis
    environment:
      - REDIS_HOST=redis
    volumes:
      - ./services/socketio:/usr/src/app
    command: ["npm", "start"]

  redis:
    image: redis:latest
    platform: linux/amd64
    ports:
      - "6379:6379"
    hostname: redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 5s
      retries: 2

  task-worker:
    platform: linux/amd64
    build:
      context: ./services/task-worker
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    volumes:
      - ./services/task-worker:/usr/src/app